version: '3.8'
services:
  stats-db:
    image: postgres:16.1
    container_name: stats-db
    ports:
      - "6541:5432"
    environment:
      - POSTGRES_USER=stats
      - POSTGRES_PASSWORD=stats
      - POSTGRES_DB=stats
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U stats -d stats"]
      interval: 5s
      timeout: 5s
      retries: 10


  stats-server:
    build: ./stats-service/stats-server
    container_name: stats-server
    ports:
      - "9090:9090"
    depends_on:
      stats-db:
        condition: service_healthy
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://stats-db:5432/stats
      SPRING_DATASOURCE_USERNAME: stats
      SPRING_DATASOURCE_PASSWORD: stats
      SPRING_PROFILES_ACTIVE: docker
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:9090/actuator/health"]
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 40s

  ewm-db:
    image: postgres:16.1
    container_name: ewm-db
    ports:
      - "6542:5432"
    environment:
      POSTGRES_USER: ewm
      POSTGRES_PASSWORD: ewm
      POSTGRES_DB: ewm
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ewm -d ewm"]
      interval: 5s
      timeout: 5s
      retries: 10

  ewm-service:
    build: ./main-service
    container_name: ewm-service
    ports:
      - "8080:8080"
    depends_on:
      ewm-db:
        condition: service_healthy
      stats-server:
        condition: service_healthy
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://ewm-db:5432/ewm
      SPRING_DATASOURCE_USERNAME: ewm
      SPRING_DATASOURCE_PASSWORD: ewm
      STATS_SERVER_URL: http://stats-server:9090
      SPRING_PROFILES_ACTIVE: docker
